# Neden NumPy

In [17]:
a = [1,2,3,4]
b = [2,3,4,5]

In [19]:
ab = []

for i in range(0,len(a)):
    ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

In [21]:
import numpy as np

In [23]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [25]:
a*b

array([ 2,  6, 12, 20])

# Özellikleri

* **ndim**: boyut sayısı
* **shape**: boyut bilgisi
* **size**: toplam eleman sayısı
* **dtype**: array veri tipi

In [32]:
import numpy as np

In [36]:
a = np.random.randint(10, size = 10)

In [38]:
a.ndim

1

In [40]:
a.shape

(10,)

In [42]:
a.size

10

In [44]:
a.dtype

dtype('int64')

In [52]:
b = np.random.randint(10, size = (3,5))

In [54]:
b

array([[5, 1, 5, 7, 6],
       [8, 3, 8, 7, 1],
       [5, 0, 7, 6, 6]])

In [56]:
b.ndim

2

In [58]:
b.shape

(3, 5)

In [60]:
b.size

15

In [64]:
b.dtype

dtype('int64')

# Yeniden Şekillendirme (reshaping)

In [67]:
import numpy as np

In [71]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
a = np.arange(1,10)

In [78]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
a.ndim

1

In [90]:
b = a.reshape((1,9))

In [94]:
b.ndim

2

# Array Birleştirme (Concatenation)

In [97]:
import numpy as np

In [99]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [103]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [139]:
#iki boyut

In [107]:
a = np.array([[1,2,3],
              [4,5,6]])

In [109]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [113]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayırma (Splitting)

In [8]:
import numpy as np

In [10]:
x = np.array([1,2,3,99,99,3,2,1])

In [12]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [14]:
a,b,c = np.split(x, [3,5])

In [16]:
a

array([1, 2, 3])

In [18]:
b

array([99, 99])

In [20]:
c

array([3, 2, 1])

In [22]:
#iki boyutlu ayırma

In [24]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [26]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [28]:
ust, alt = np.vsplit(m, [2])

In [30]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [32]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
sag, sol = np.hsplit(m, [2])

In [38]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [40]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Sıralama (Sorting)

In [45]:
import numpy as np

In [47]:
v = np.array([2,1,4,3,5])

In [49]:
v

array([2, 1, 4, 3, 5])

In [53]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [55]:
v.sort() #kalıcı olarak array'ı değiştirir

In [57]:
v

array([1, 2, 3, 4, 5])

In [61]:
#numpy'ın içerisinden sort fonksiyonu çağırdığımızda array kalıcı olarak değişmez

In [63]:
m = np.random.normal(20,5,(3,3))

In [65]:
m

array([[23.38529865, 12.23450105, 17.92168234],
       [12.10959304, 18.30888247, 18.92133523],
       [22.5526851 , 16.55308691, 21.19780343]])

In [67]:
np.sort(m, axis = 1)

array([[12.23450105, 17.92168234, 23.38529865],
       [12.10959304, 18.30888247, 18.92133523],
       [16.55308691, 21.19780343, 22.5526851 ]])

In [69]:
np.sort(m, axis = 0)

array([[12.10959304, 12.23450105, 17.92168234],
       [22.5526851 , 16.55308691, 18.92133523],
       [23.38529865, 18.30888247, 21.19780343]])

# Index ile Elemanlara Erişmek

In [72]:
import numpy as np

In [84]:
a = np.random.randint(10, size = 10)
a

array([6, 8, 7, 4, 1, 3, 4, 9, 9, 2])

In [86]:
a[0]

6

In [88]:
a[-1]

2

In [90]:
a[0] = 100

In [92]:
a

array([100,   8,   7,   4,   1,   3,   4,   9,   9,   2])

In [96]:
m = np.random.randint(10, size = (3,5))
m

array([[1, 7, 4, 3, 9],
       [7, 7, 0, 0, 7],
       [4, 9, 4, 1, 7]])

In [100]:
m[1,1]

7

In [102]:
m[1,4] = 2.2

In [104]:
m

array([[1, 7, 4, 3, 9],
       [7, 7, 0, 0, 2],
       [4, 9, 4, 1, 7]])

# Array Alt Küme İşlemleri

In [107]:
import numpy as np

In [111]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [113]:
a[0:3]

array([20, 21, 22])

In [115]:
a[2::2]

array([22, 24, 26, 28])

In [117]:
#iki boyutlu slice islemleri

In [119]:
m = np.random.randint(10, size = (5,5))

In [ ]:
m

In [123]:
m[:,0]

array([0, 6, 2, 1, 2])

In [125]:
m[0,:]

array([0, 1, 2, 4, 9])

In [127]:
m[1,:]

array([6, 6, 6, 7, 6])

In [129]:
m[0:2,0:3]

array([[0, 1, 2],
       [6, 6, 6]])

# Alt Küme Üzerinde İşlem Yapmak

In [2]:
import numpy as np
a = np.random.randint(10, size = (5,5))
a

array([[3, 9, 3, 2, 6],
       [6, 6, 8, 7, 7],
       [0, 7, 8, 9, 5],
       [7, 5, 9, 1, 8],
       [1, 6, 7, 6, 2]])

In [8]:
alt_a = a[0:3, 0:2]
alt_a

array([[3, 9],
       [6, 6],
       [0, 7]])

In [14]:
alt_a[0,0] = 9999
alt_a[1,1] = 888

In [16]:
alt_a

array([[9999,    9],
       [   6,  888],
       [   0,    7]])

In [18]:
a

array([[9999,    9,    3,    2,    6],
       [   6,  888,    8,    7,    7],
       [   0,    7,    8,    9,    5],
       [   7,    5,    9,    1,    8],
       [   1,    6,    7,    6,    2]])

In [20]:
m = np.random.randint(10, size = (5,5))
m

array([[2, 4, 2, 4, 7],
       [4, 7, 5, 7, 1],
       [3, 0, 2, 7, 6],
       [5, 0, 9, 5, 3],
       [9, 6, 3, 4, 7]])

In [26]:
alt_m = m[0:3, 0:2].copy()
alt_m

array([[2, 4],
       [4, 7],
       [3, 0]])

In [30]:
alt_m[0,0] = 9999
alt_m

array([[9999,    4],
       [   4,    7],
       [   3,    0]])

In [32]:
m

array([[2, 4, 2, 4, 7],
       [4, 7, 5, 7, 1],
       [3, 0, 2, 7, 6],
       [5, 0, 9, 5, 3],
       [9, 6, 3, 4, 7]])

# Fancy Index ile Elemanlara Erişmek

In [35]:
import numpy as np
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [37]:
v[1]

3

In [39]:
v[3]

9

In [41]:
v[5]

15

In [43]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [45]:
al_getir = [1,3,5]

In [47]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [49]:
v[al_getir]

array([ 3,  9, 15])

In [51]:
#iki boyutlu fancy

In [65]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [69]:
m[satir, sutun]

array([1, 5])

In [71]:
#basit index ile fancy index

In [75]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
m[0, [1,2]]

array([1, 2])

In [81]:
#slice ile fancy

In [79]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri

In [85]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [91]:
v < 3

array([ True,  True, False, False, False])

In [93]:
v[v < 3]

array([1, 2])

In [97]:
v[v <= 3]

array([1, 2, 3])

In [101]:
v[v != 3] #3'ün dışındakileri getir

array([1, 2, 4, 5])

In [103]:
v[v == 3]

array([3])

In [105]:
v * 5

array([ 5, 10, 15, 20, 25])

In [107]:
v / 2

array([0.5, 1. , 1.5, 2. , 2.5])

# Matematiksel İşlemler

In [113]:
import numpy as np
v = np.array([1,2,3,4,5])

In [115]:
v - 1

array([0, 1, 2, 3, 4])

In [117]:
v * 5

array([ 5, 10, 15, 20, 25])

In [119]:
#ufunc

In [123]:
np.subtract(v, 1) #v - 1 işleminin arkasında dönen işlem aslında bu

array([0, 1, 2, 3, 4])

In [125]:
np.add(v, 1) #v + 1 işleminin arkasında dönen işlem aslında bu

array([2, 3, 4, 5, 6])

In [129]:
np.multiply(v,4) #v * 4 işleminin arkasındaki işlem

array([ 4,  8, 12, 16, 20])

In [133]:
np.divide(v, 3) #v / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [135]:
np.power(v, 3) #v**2

array([  1,   8,  27,  64, 125])

In [139]:
np.mod(v,2) #v % 2, yani 'ye bölümünden kalanı getirir

array([1, 0, 1, 0, 1])

In [141]:
np.sin(360)

0.9589157234143065

In [143]:
np.cos(180)

-0.5984600690578581

In [145]:
v = np.array([1,2,3])

In [147]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [149]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [151]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [153]:
?np

Type:        module
String form: <module 'numpy' from '/opt/anaconda3/lib/python3.11/site-packages/numpy/__init__.py'>
File:        /opt/anaconda3/lib/python3.11/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = 

# NumPy ile İki Bilinmeyenli Denklem Çözümü

In [3]:
import numpy as np

In [10]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [12]:
a

array([[5, 1],
       [1, 3]])

In [14]:
b

array([12, 10])

In [16]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])